name: Collect time series

# This workflow will run on push or pull requests to the main branch
on:
  # schedule:
  #  - cron: '*/10 * * * *'
  push:
    branches: [master]

jobs:
  render:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver:latest
    permissions:
      contents: write  # Grant write permissions to the repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Install R dependencies
      run: |
        Rscript -e "install.packages('renv', repos = 'https://packagemanager.posit.co/cran/latest')"
        Rscript -e "renv::restore(repos = 'https://packagemanager.posit.co/cran/latest')"
        
    - name: Collect data with pins
      run: |
        Rscript pins-demo.R
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}} 
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION}}
